spring.application.name=hostpital-management-system-frontend
# Port for this Frontend project
server.port=8088

# The URL of your running Backend API
hms.backend.url=http://localhost:8089

# Thymeleaf Cache (Set to false during development so changes show instantly)
spring.thymeleaf.cache=false